// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_5CS8O9mcD8rQ70hKkB-ctbf9aJMP984',
    appId: '1:25708222196:web:cef8bd156f7d8b5af1b0a1',
    messagingSenderId: '25708222196',
    projectId: 'fir-test-d6b89',
    authDomain: 'fir-test-d6b89.firebaseapp.com',
    storageBucket: 'fir-test-d6b89.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzc5R51SeoC7bdXLwJjEB2XfZVpnQygbk',
    appId: '1:25708222196:android:738f115d65bd59b9f1b0a1',
    messagingSenderId: '25708222196',
    projectId: 'fir-test-d6b89',
    storageBucket: 'fir-test-d6b89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAencQkgjdZZmnewSRm0iiuaEkRo7eroXg',
    appId: '1:25708222196:ios:4c2ab07d56e7d1d7f1b0a1',
    messagingSenderId: '25708222196',
    projectId: 'fir-test-d6b89',
    storageBucket: 'fir-test-d6b89.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAencQkgjdZZmnewSRm0iiuaEkRo7eroXg',
    appId: '1:25708222196:ios:372dc683fe02baf3f1b0a1',
    messagingSenderId: '25708222196',
    projectId: 'fir-test-d6b89',
    storageBucket: 'fir-test-d6b89.appspot.com',
    iosBundleId: 'com.example.firebase.RunnerTests',
  );
}
